# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

winzou_state_machine:
    sylius_shipment:
        class: "%sylius.model.shipment.class%"
        property_path: state
        graph: sylius_shipment
        states:
            cart: ~
            ready: ~
            shipped: ~
            cancelled: ~
        transitions:
            create:
                from: [cart]
                to: ready
            ship:
                from: [ready]
                to: shipped
            cancel:
                from: [ready]
                to: cancelled
