Sylius\Component\Shipping\Model\ShipmentUnit:
    exclusion_policy: ALL
    xml_root_name: shipment-unit
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        shippingState:
            expose: true
            type: string
        createdAt:
            expose: true
            type: DateTime
        updatedAt:
            expose: true
            type: DateTime
