Sylius\Component\Shipping\Model\Shipment:
    exclusion_policy: ALL
    xml_root_name: shipment
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        state:
            expose: true
            type: string
            groups: [Default, Detailed]
        method:
            expose: true
            groups: [Default, Detailed]
        tracking:
            expose: true
            groups: [Default, Detailed]
    relations:
        - rel: self
          exclusion:
                exclude_if: expr(!object.getId())
          href:
                route: sylius_api_shipment_show
                parameters:
                    id: expr(object.getId())
                    version: 1
        - rel: shipping-method
          exclusion:
                exclude_if: expr(!object.getMethod())
          href:
                route: sylius_api_shipping_method_show
                parameters:
                    code: expr(object.getMethod().getCode())
                    version: 1
